server:
  port: 8020

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.68.2:8848,172.22.69.2:8848,172.22.70.2:8848
        namespace: 1d87c0e0-6950-45cb-b4ef-ed969eab7e49

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.22.68.20:3306/seata-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

logging:
  level:
    com.ww: debug

seata:
  application-id: ${spring.application.name}
  # seata 服务分组，要与服务端配置service.vgroup_mapping的后缀对应
  tx-service-group: ${spring.application.name}-seata-service-group
  registry:
    # 指定nacos作为注册中心
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.22.68.2:8848,172.22.69.2:8848,172.22.70.2:8848
      namespace: 1d87c0e0-6950-45cb-b4ef-ed969eab7e49
      group: DEFAULT_GROUP
      cluster: default

  config:
    # 指定nacos作为配置中心
    type: nacos
    nacos:
      server-addr: 172.22.68.2:8848,172.22.69.2:8848,172.22.70.2:8848
      namespace: 1d87c0e0-6950-45cb-b4ef-ed969eab7e49
      group: DEFAULT_GROUP
      data-id: seataServer.properties

#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
#feign:
#  sentinel:
#    enabled: true